version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest  # Docker image for building the application
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            npm install --prefix payments-portal/backend
      - run:
          name: "Build Application"
          command: |
            npm run build --prefix payments-portal/backend

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            npm install --prefix payments-portal/backend
      - run:
          name: "Run Tests"
          command: |
            npm test --prefix payments-portal/backend

  sonarqube_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: "Run SonarQube Scan"
          command: |
            cd payments-portal/backend && sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="$SONAR_HOST_URL" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.sources="." \
              -Dsonar.branch.name="${CIRCLE_BRANCH}" \
              -Dsonar.exclusions="**/*.c,**/*.cpp,**/*.h,**/tests/**" \
              -Dsonar.c.file.suffixes=- \
              -Dsonar.cpp.file.suffixes=- \
              -Dsonar.objc.file.suffixes=-

workflows:
  version: 2
  devsecops_pipeline:
    jobs:
      - build
      - test
      - sonarqube_scan:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - Dillon
                - Alison
                - Devania
                - Tawfiq
