version: 2.1

jobs:
  sonarqube_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Docker image with SonarQube scanner
    steps:
      - checkout  # Checks out your code from GitHub
      - run:
          name: "Install Dependencies"
          command: |
            # Install any dependencies here, if necessary
            echo "Installing dependencies if required"
- run:
    name: "Run SonarQube Scan"
    command: |
      sonar-scanner \
        -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
        -Dsonar.organization="$SONAR_ORG" \
        -Dsonar.host.url="$SONAR_HOST_URL" \
        -Dsonar.login="$SONAR_TOKEN" \
        -Dsonar.sources="." \
        -Dsonar.branch.name="${CIRCLE_BRANCH}" \
        -Dsonar.exclusions="**/tests/**" \
        -Dsonar.c.file.suffixes=- \
        -Dsonar.cpp.file.suffixes=- \
        -Dsonar.objc.file.suffixes=-

workflows:
  version: 2
  sonar_scan_workflow:
    jobs:
      - sonarqube_scan:
          filters:
            branches:
              only:
                - main
                - Dillon
                - Alison
                - Devania
                - Tawfiq
